services:
  - type: web
    name: assignment-3
    runtime: node
    buildCommand: npm install
    startCommand: node ./bin/www
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
